global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'snmp'
    static_configs:
      - targets:
        - '10.192.172.254' # Replace with your SNMP device IP
    metrics_path: /snmp
    params:
      module: [if_mib] # Modify based on the SNMP module
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance